### ISSUE TITLE
Failed to send MCASH using easytransferbyprivate RPC method

### ISSUE THREAD

**Issue by szhelonkin** [MidasCore/java-mcashchain#3]
Failed to send MCASH using easytransferbyprivate RPC method.
{"result"=>{"code"=>"CONTRACT_VALIDATE_ERROR", "message"=>"313a39363a20494e56414c49442068657820537472696e67"}}

**Comment by nghiand** [comment]
I've successfully sent MCASH using this api.
Did your request use address in base58? Please try **to_address** and **memo** (optional) in hex format.

**Comment by szhelonkin** [comment]
Yes address in base58 for example MHcBgQK9QsctfoWsWQ5NWRiEwvcysvUQMv.
It works fine before 12-2019 after that we always have validate error.

**Comment by nghiand** [comment]
The Api does not accept address in base58, so please use hex format instead.
**326a7b6522282f37d09d77527f28508407b88c583d** for your example **MHcBgQK9QsctfoWsWQ5NWRiEwvcysvUQMv**

**Comment by szhelonkin** [comment]
Yes it works fine.
It it possible to get hex fromat from base58 using api?
